### ISSUE TITLE
ワークフローにPrettierとblackのコードフォーマッタを追加し、差分がある場合にCIをエラーで落とす

### ISSUE THREAD

**Issue by nata-water** [shinno21/monorepo_apps#13]

**Comment by nata-water** [comment]
@shinno21 
本件、対応自体は完了してます。
お手数ですが、もう一度monorepo_appsにコラボレーターとして招待してもらっても良いでしょうか。
コラボ招待の有効期限が切れる前に、「Accept」すべきだったのですが、実施しておらず・・・。

forkedリポジトリからではなく、このリポジトリにfeatureブランチ切ってPushしようとしたのですが、権限エラーで落ちました。

**Comment by shinno21** [comment]
@nata-water 
返事遅れてごめん。今招待しました！

**Comment by nata-water** [comment]
無事にマージ完了したためクローズします。
